<?php header('Content-Type: text/html; charset=UTF-8');?>
<form id="frmData" action="saveEstrategia.php" method="post" >
  <div>
    <table border="0" class="tbComun">
      <tbody>

        <strong></strong>
        <input type="text" name="nameNombre" id="nombre_x" class="camposEntradaEstrategia" placeholder="NUEVA CATEGORÍA ESTRATÉGICA"/>
        <br>
        </br>
        <br>
        </br>
        <input class="boton_guardar" type="submit" name="btnGuardarEstrategia" value="Guardar Categorias" />
        <input class="btnVerEstrategia" type="submit" name="btnVerEstrategia" value="Ver Registros" />
      </tbody>
    </table>
  </div>
</form>

<footer class="fotterMQA">
  <img src="temas/img/mqa.png" width="100" height="45" />
  <div>&#174; Marca Registrada</div>

</footer>


