<?php header('Content-Type: text/html; charset=UTF-8');?>
<form id="frmData" action="SaveEstrategiaCliente.php" method="post" >
  <div>
    <table border="0" class="tbComun">
      <tbody>
        <tr>
          <th>
            <label for="nombre_x"></label>
          </th>
          
            <td><input type="text" name="nameNombre" id="nombre_x" class="camposEntradaCliente" placeholder="NUEVA CATEGORÍA CLIENTE"/>
              </td>
          
        </tr>
       
      


      </tbody>
    </table>
    <br>
    </br>
    <br>
    </br>
    <br>
    </br>
    <input class="boton_guardar" type="submit" name="btnGuardarCliente" value="Guardar Categorias" />
    <input class="btnVerEstrategia" type="submit" name="btnVerEstrategia" value="Ver Registros" />
  </div>




</form>
<footer class="fotterMQA">
  <img src="temas/img/mqa.png" width="100" height="45" />
  <div>&#174; Marca Registrada</div>

</footer>

