<form id="frmData" action="./" method="post" >
	<div> 
		<table border="0" class="tbComun"> 
			<tbody> 
				<tr> 
					<th><label for="nombre_x"></label></th>
        
     		<td><input type="text" name="nombre[]" id="nombre_x" class="camposEntradaMesas" placeholder="MESA NUEVA"></td> 
				</tr> 
			</tbody> 
		</table>
		<input type="hidden" name="visiblesugerencias[]" id="visiblesugerencias_x" value="0">
		<input type="hidden" name="talleres_id[]" id="talleres_id_x" value="1">
	</div> 
	<input type="hidden" name="id[]" id="id_x" value="" />
	<input type="hidden" name="pageid" value="modelos/<?php echo basename( __FILE__ ); ?>" /> 
	<input type="hidden" name="jsmenuid" value="<?php echo $_POST[ "jsmenuid" ]; ?>" /> 
	<input class="boton_guardar" type="submit" name="cmd" value="Guardar Mesas" /> 
</form> 
<div id="frmVista" class="frmVistaOculta" > 
	<?php echo Utiles::BarraPaginacion(basename( __FILE__ ), $_POST[ "jsmenuid" ]); ?>
	<?php echo $this->obtenerTablaConLlaves(); ?>
	<?php echo Utiles::BarraPaginacion(basename( __FILE__ ), $_POST[ "jsmenuid" ]); ?>
</div>




<script type="text/javascript">
//Paginación:
<?php if( isset($_POST["paginaV"]) ): ?>
	jQuery("#frmData").hide();
	jQuery("#frmVista").show();
<?php endif; ?>

$(".ico_actualizar").hide();
</script>
<footer class="fotterMQA">
  <img src="temas/img/mqa.png" width="100" height="45" />
  <div>&#174; Marca Registrada</div>

</footer>